/**
 * Copyright (c) 2018 Araf Karsh Hamid

 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.

 * This program and the accompanying materials are dual-licensed under
 * either the terms of the Eclipse Public License v1.0 as published by
 * the Eclipse Foundation
 
 *   or (per the licensee's choosing)
 
 * under the terms of the Apache 2 License version 2.0
 * as published by the Apache Software Foundation.
*/
package org.amexio.colors.io;

import java.util.Comparator;
import java.util.StringJoiner;

import org.amexio.colors.core.Color;
import org.amexio.colors.core.ColorAlgoConstants;
import org.amexio.colors.web.Colors;

/**
 * Theme Configuration Object
 * 
 * @author Araf Karsh Hamid
 * @version 1.0
 * @date
 */
public final class ThemeConfig implements Comparable<ThemeConfig>, Comparator<ThemeConfig> {
	private static final String NL = "";
	
	private final String fileName;
	private final String themeInitFile;
	private final String themeBootFile;
	private final String themeJSONFile;
	private final String themeCssFile;
	private final String themeImageName;
	
	private final String color1;
	private String color2;
	private String color3;
	private String color4;
	private String color5;
	private String color6;
	private final String themeName;
	
	private final Color primaryColor;
	
	private final String navBarBGColor;
	private final String navBarFontColor;
	private int rgbValue = -1;
	private int hue = -1;
	
	private final String mdaPath = "../node_modules/amexio-ng-extensions/styles/mda/";

	private final int colorAlgo;
	
	private double version = 3.0;
	private String releaseDate = "";
	private boolean isMaterial = true;
	
	/**
	 * 
	 */
	public ThemeConfig() {
		this(0, "invalid-theme-file","#990000","#ff0000");
	}
	/**
	 * Theme Data Reader (Row)
	 * 1. Theme Init File Name
	 * 2. Primary Color
	 * 
	 * @param _file
	 * @param _c1
	 */
	public ThemeConfig(int _colorAlgo, String _file, String _c1) {
		this(_colorAlgo, _file, _c1, null, null, null, null, null);
	}
	
	/**
	 * Theme Data Reader (Row)
	 * 1. Theme Init File Name
	 * 2. Primary Color
	 * 3. Secondary Color
	 * 
	 * @param _file
	 * @param _c1
	 * @param _c2
	 */
	public ThemeConfig(int _colorAlgo, String _file, String _c1, String _c2) {
		this(_colorAlgo, _file, _c1, _c2, null, null, null, null);
	}
	
	/**
	 * Theme Data Reader (Row)
	 * 1. Theme Init File Name
	 * 2. Primary Color
	 * 3. Secondary Color
	 * 4. Teritiary Color
	 * 5. Fourth Color
	 * 
	 * @param _file
	 * @param _c1
	 * @param _c2
	 * @param _c3
	 * @param _c4
	 */
	public ThemeConfig(int _colorAlgo, String _file, String _c1, String _c2, 
			String _c3, String _c4) {
		this(_colorAlgo, _file, _c1, _c2, _c3, _c4, null, null);
	}
	
	/**
	 * Theme Data Reader (Row)
	 * 1. Theme Init File Name
	 * 2. Primary Color
	 * 3. Secondary Color
	 * 4. Teritiary Color
	 * 5. Fourth Color
	 * 6. Fifth COlor
	 * 7. Sixth Color
	 * 
	 * @param _file
	 * @param _c1
	 * @param _c2
	 * @param _c3
	 * @param _c4
	 * @param _c5
	 * @param _c6
	 */
	public ThemeConfig(int _colorAlgo, String _file, String _c1, String _c2, String _c3,
			String _c4, String _c5, String _c6) {
		
		colorAlgo		= _colorAlgo;
		
		fileName		= setFileName(_file);
		themeCssFile	= makeThemeCssFile();
		themeInitFile	= makeInitFileName();
		themeBootFile	= makeBootFileName();
		themeJSONFile	= makeJSONFileName();
		themeName		= createThemeName();
		themeImageName	= makeImageFileName();
		color1			= (_c1 != null) ? _c1.trim() : Colors.RED.DARKRED.hexStr();
		color2		  	= _c2;
		color3			= _c3;
		color4			= _c4;
		color5			= _c5;
		color6			= _c6;
		/**

		*/
		primaryColor	= new Color(color1);
		navBarBGColor	= primaryColor.hexStr();
		navBarFontColor	= primaryColor.foregroundColor().hexStr();
		rgbValue		= primaryColor.rgb();
		hue				= primaryColor.hue();
	} 
	
	/**
	 * Auto Generated Theme Color - Derived from the Primary Color - Theme Color 1
	 * 
	 * @param _c2
	 * @param _c3
	 * @param _c4
	 * @param _c5
	 * @param _c6
	 */
	public void setAutoGeneratedThemeColors(String _c2, String _c3, String _c4, String _c5, String _c6) {
		color2 = (_c2 != null) ? _c2.trim() :  Colors.BROWN.BURLYWOOD.hexStr();
		color3 = (_c3 != null) ? _c3.trim() :  Colors.ORANGE.CORAL.hexStr();
		color4 = (_c4 != null) ? _c4.trim() :  Colors.GREEN.MEDIUMSPRINGGREEN.hexStr();
		color5 = (_c5 != null) ? _c5.trim() :  Colors.WHITE.WHITESMOKE.hexStr();
		color6 = (_c6 != null) ? _c6.trim() :  Colors.WHITE.WHITE.hexStr();
	}
	
	/**
	 * Returns the Primary Color
	 * 
	 * @return
	 */
	public Color getPrimaryColor() {
		return primaryColor;
	}
	
	/**
	 * Returns the Color Algo
	 * 
	 * @return
	 */
	public int getColorAlgo() {
		return colorAlgo;
	}
	
	/**
	 * Returns the Theme Release Date
	 * @return
	 */
	public String getReleaseDate() {
		return releaseDate;
	}
	
	/**
	 * Set the Theme File Name
	 * @param _fileName
	 * @return
	 */
	private String setFileName(String _fileName) {
		if(_fileName == null || _fileName.length() == 0) {
			return "no-name";
		}
		return _fileName.trim();
	}
	
	/**
	 * Creates the Theme CSS name
	 * @return
	 */
	private String makeThemeCssFile() {
		return "at-md-" + fileName.toLowerCase();
	}
	
	/**
	 * Theme Image File Name
	 * @return
	 */
	private String makeImageFileName() {
		return "AT-MD-" + themeName.replace(" ", "-") + ".jpg";
	}
	
	/**
	 * Make Init File Name
	 * @return
	 */
	private String makeInitFileName() {
		return "at-md-" + fileName.toLowerCase() + "-init.scss";
	}

	/**
	 * Make Boot File Name
	 * @return
	 */
	private String makeBootFileName() {
		return "at-md-" + fileName.toLowerCase() + ".scss";
	}
	
	/**
	 * Make the JSON File Name
	 * @return
	 */
	private String makeJSONFileName() {
		return "at-md-" + fileName.toLowerCase() + ".json";
	}

	/**
	 * Create the Theme Name
	 * @return
	 */
	private String createThemeName() {
		char[] c = fileName.trim().replaceAll("-", " ").toCharArray();
		int y = 0;
		for(int x=0; x<c.length; x++) {
			if(x==0 || x==y) c[x] = (char) (c[x] - 32);
			if(c[x] == 32) y = x +1;
		}
		return new String(c);
	}
	/**
	 * Set the Theme Version
	 * @param _version
	 * @return
	 */
	public ThemeConfig setVersion(double _version) {
		if(_version > 0.0) {
			version = _version;
		}
		return this;
	}
	
	/**
	 * Sets the Design Type 
	 * TRUE = Material Design
	 * FALSE = Amexio Design
	 * 
	 * @param _type
	 * @return
	 */
	public ThemeConfig setDesignType(boolean _type) {
		isMaterial = _type;
		return this;
	}
	
	/**
	 * Sets the Theme Release Date
	 * @param _date
	 * @return
	 */
	public ThemeConfig setReleaseDate(String _date) {
		releaseDate = (_date == null) ? "Not Available" : _date;
		return this;
	}
	
	/**
	 * Sets the Theme Design Type to Material Design
	 * @return
	 */
	public ThemeConfig setMaterialDesignType() {
		isMaterial = true;
		return this;
	}
	
	/**
	 * Sets the Theme Design Type to Amexio Design
	 * @return
	 */
	public ThemeConfig setAmexioDesignType() {
		isMaterial = false;
		return this;
	}
	
	/**
	 * Returns TRUE if the Design Type = Material Design
	 * @return
	 */
	public boolean isMaterial() {
		return isMaterial;
	}
	
	/**
	 * Returns the Design Type
	 * @return
	 */
	public String designType() {
		return (isMaterial) ? "Material Design" : "Amexio Design";
	}
	
	/**
	 * Returns the Version
	 * @return
	 */
	public double getVersion() {
		return version;
	}
	
	/**
	 * Returns Theme Input Name
	 * @return
	 */
	public String getThemeInputName() { return fileName; }
	
	/**
	 * Returns the Theme Init File Name
	 * @return
	 */
	public String getThemeInitFile() { return themeInitFile; }
	
	/**
	 * Returns the Theme Boot File
	 * @return
	 */
	public String getThemeBootFile() { return themeBootFile; }

	/**
	 * Theme JSON File with Theme MetaData and CSS3 Vars
	 * @return
	 */
	public String getThemeJSONFile() { return themeJSONFile; }
	/**
	 * Returns the CSS File name
	 * @return
	 */
	public String getCssFileName() { return themeCssFile + ".css"; }
	/**
	 * Returns the Theme Material Selector Data File Name
	 * @return
	 */
	public String getThemeMaterialFileName() { return "material.json"; }
	
	/**
	 * Returns the Theme Name
	 * @return
	 */
	public String getThemeName() { return themeName; }
	
	public Integer getRGBValue() { return rgbValue; }
	
	public Integer getHueValue() { return hue; }
	
	/**
	 * Return the Primary Color
	 * @return
	 */
	public String getColor1() { return color1; }
	
	/**
	 * Return the Secondary Color
	 * @return
	 */
	public String getColor2() { return color2; }

	/**
	 * Return Teritiary Color
	 * @return
	 */
	public String getColor3() { return color3; }
	
	/**
	 * Return the Fourth Color
	 * @return
	 */
	public String getColor4() { return color4; }
	
	/**
	 * Return the Fifth Color
	 * @return
	 */
	public String getColor5() { return color5; }
	
	/**
	 * Return the 6th Color
	 * @return
	 */
	public String getColor6() { return color6; }
	
	/**
	 * Returns the Hash Code of the Theme Input File Name
	 */
	public int hashCode() {
		return fileName.hashCode();
	}
	
	/**
	 * Sort on Theme Name
	 */
	@Override
	public int compareTo(ThemeConfig _theme) {
		return (_theme == null) ? 0 : this.themeName.compareTo(_theme.themeName);
	}
	
	/**
	 * Compare Two ThemeConfig Objects
	 */
	@Override
	public int compare(ThemeConfig _tc1, ThemeConfig _tc2) {
		return (_tc1 == null) ? 0 : _tc1.compareTo(_tc2);
	}
	
	/**
	 * Theme Data
	 */
	public String toString() {
		StringJoiner sj = new StringJoiner(",");
		sj.add(fileName).add(color1).add(color2);
		sj.add(designType()).add(""+getVersion());
		return sj.toString();
	}
	
	/**
	 * Builds the JSON Structure for Theme Selector
	 * 
	 * @return
	 */
	public String toJSON() {
		StringBuilder sb = new StringBuilder();
		String theme = themeNameCorrection(this.themeName);
		sb.append("{").append(NL);
		sb.append("\"themeName\": \"").append(theme.trim()).append("\",").append(NL);
		sb.append("\"style\": \"").append(this.designType()).append("\",").append(NL);
		sb.append("\"releaseDate\": \"").append(this.getReleaseDate()).append("\",").append(NL);
		sb.append("\"version\": ").append(this.version).append(",").append(NL);	
		sb.append("\"algorithmName\": \"").append(ColorAlgoConstants.ALGO_NAMES[this.colorAlgo]).append("\",").append(NL);
		sb.append("\"algorithmID\": ").append(this.colorAlgo).append(",").append(NL);
		sb.append("\"rgb\": ").append(this.rgbValue).append(",").append(NL);
		sb.append("\"hue\": ").append(this.hue).append(",").append(NL);
		sb.append("\"themes\": [");
		sb.append("\"").append(color1).append("\",");
		sb.append("\"").append(color2).append("\",");
		sb.append("\"").append(color3).append("\",");
		sb.append("\"").append(color4).append("\",");
		sb.append("\"").append(color5).append("\",");
		sb.append("\"").append(color6).append("\"");
		sb.append("],").append(NL);
		sb.append("\"navBarBGColor\": \"").append(this.navBarBGColor).append("\",").append(NL);
		sb.append("\"navBarFontColor\": \"").append(this.navBarFontColor).append("\",").append(NL);
		sb.append("\"themeFilePath\": \"").append(this.mdaPath).append(this.themeBootFile).append("\",").append(NL);
		sb.append("\"themeJSONFile\": \"").append(this.themeJSONFile).append("\",").append(NL);
		sb.append("\"themeCSS3File\": \"").append(this.themeCssFile).append(".scss\",").append(NL);
		sb.append("\"themeImageFile\": \"").append(this.themeImageName).append("\"").append(NL);
		sb.append("}");
		return sb.toString();
	}
	
	public String toAPIDocsJSON() {
		StringBuilder sb = new StringBuilder();
		String theme = themeNameCorrection(this.themeName);
		sb.append("{").append(NL);
		sb.append("\"name\": \"").append(theme.trim()).append("\",").append(NL);
		sb.append("\"releaseDate\": \"").append(this.getReleaseDate()).append("\",").append(NL);
		sb.append("\"version\": ").append(this.version).append(",").append(NL);	
		sb.append("\"algorithmName\": \"").append(ColorAlgoConstants.ALGO_NAMES[this.colorAlgo]).append("\",").append(NL);
		sb.append("\"themes\": [");
		sb.append("\"").append(color1).append("\",");
		sb.append("\"").append(color2).append("\",");
		sb.append("\"").append(color3).append("\",");
		sb.append("\"").append(color4).append("\",");
		sb.append("\"").append(color5).append("\",");
		sb.append("\"").append(color6).append("\"");
		sb.append("],").append(NL);
		sb.append("\"description\": \"").append(this.mdaPath).append(this.themeBootFile).append("\"").append(NL);
		sb.append("}");
		return sb.toString();
	}
	
	private String themeNameCorrection(String _themeName) {
		if(_themeName == null) {
			return "No-Name-Theme";
		}
		String t = _themeName.trim();
		if(_themeName.trim().startsWith("Z ")) {
			t = _themeName.replaceAll("Z Flag ","").replaceAll("Z Ce", "");
		}
		return t;
	}
}
